Initial commit
hazelops/charts pull request #12
Opened 2023-09-27 19:09 UTC by kobrikx

#### What's new:

 - Initial commit

2023-09-27 21:48 UTC, AutomationD requested changes
Mostly looks good, have some questions, please address them and feel free to merge.

Please create a story to join two charts into one and add a selector to create istio gateway/nginx ingress or select them as a config.

2023-09-27 21:48 UTC, AutomationD commented on .github/workflows/release-helm-charts.yml
> +      - develop
Please make repo's main branch to be develop

2023-09-27 21:48 UTC, AutomationD commented on charts/web-app-ext-cert/templates/istio-gateway.yaml
> +        - {{ .Values.app.name}}.{{ .Values.env}}.{{.Values.istio.domain}}
Let's add a brand domain here and in the TLS via another story if we can't do it within the current one.

2023-09-27 21:48 UTC, AutomationD commented on charts/web-app-ext-cert/values.yaml
> +  app: global
Can we we read `/env/squibby/<secret-name>` or only global?
IF we can't, let's add a separate story for this.

2023-09-27 21:48 UTC, AutomationD commented on charts/web-app/templates/deployment.yaml
> +  # Use the same namespace we created
Created where? 🤔 (don't use `same`, just `Use the namespace we created in this chart`

2023-09-27 21:48 UTC, AutomationD commented on charts/web-app/templates/external-secret.yaml
> +{{ end }}
Shouldn't this be indented by 2 levels?

2023-09-27 21:48 UTC, AutomationD commented on charts/web-app-ext-cert/Chart.yaml
> +description: Web-app for use with already installed Istio or Ingress-nginx
```suggestion
description: Web-app for a cluster with Istio or Ingress-nginx
```

2023-09-27 21:48 UTC, AutomationD commented on charts/web-app-ext-cert/Chart.yaml
> +name: web-app-without-ingress
Doesn't correspond to directory name

2023-09-27 21:48 UTC, AutomationD commented on charts/web-app-ext-cert/Chart.yaml
> +name: web-app-without-ingress
Also, it's not clear why is it ext-cert?

2023-09-27 22:43 UTC, kobrikx commented on .github/workflows/release-helm-charts.yml
> +      - develop
ok

2023-09-27 22:44 UTC, kobrikx commented on charts/web-app-ext-cert/templates/istio-gateway.yaml
> +        - {{ .Values.app.name}}.{{ .Values.env}}.{{.Values.istio.domain}}
Please clarify, what do you want? I don't quite understand.Sorry.

2023-09-27 22:46 UTC, kobrikx commented on charts/web-app-ext-cert/values.yaml
> +  app: global
We can, but this chart is intended to be used with the global.

2023-09-27 22:47 UTC, kobrikx commented on charts/web-app/templates/external-secret.yaml
> +{{ end }}
Please clarify, what do you mean? Thank you.

2023-09-28 06:22 UTC, AutomationD commented on charts/web-app/templates/external-secret.yaml
> +{{ end }}
From style prospective the closing `{{ end }}` should be indented on the same level as the opening loop. Does it make sense?

2023-09-28 09:07 UTC, merged