Datadog options integrated
hazelops/charts pull request #39
Opened 2024-06-19 12:06 UTC by kobrikx

#### What's new:

 - Datadog settings added for deployment
 - Datadog ruby settings added for deployment
 - Linted

#### Testing done:

<img width="796" alt="Screenshot 2024-06-19 at 15 04 56" src="https://github.com/hazelops/charts/assets/24703846/16905616-9b94-4d99-b849-eb3b97481d30">

<img width="1680" alt="Screenshot 2024-06-19 at 15 05 27" src="https://github.com/hazelops/charts/assets/24703846/edefce23-1204-443b-9e80-2805d9a6e0d8">

2024-06-19 16:42 UTC, AutomationD requested changes
Good work, thank you. Please check on my comments

2024-06-19 16:42 UTC, AutomationD commented on charts/web/templates/deployment.yaml
> +        "source": "ruby",
Needs to be parametrized to support other types of sources. Also values file should have a link to the source options possible.

2024-06-19 16:42 UTC, AutomationD commented on charts/web/templates/deployment.yaml
> +        "auto_multi_line_detection": true
Should be parameterized with defaults set to true

2024-06-19 16:42 UTC, AutomationD commented on charts/web/values.schema.json
> +                      "type": "number"
Can you please explain why this change is required? Is it related to helm version update?

2024-06-19 16:42 UTC, AutomationD commented on charts/web/values.yaml
> +    enabled: true
let's not enable it by default at this time please. Otherwise we'll have to make sure README talks about "we don't support apps without datadog"

WDYT?

2024-06-19 16:42 UTC, AutomationD commented on charts/web/values.yaml
> +    version: "v7.54"
Let's add a comment where is this coming from

2024-06-19 16:42 UTC, AutomationD commented on charts/web/values.yaml
> +    ruby_lib_version: "v1.23.1"
Let's add a comment where is this coming from

2024-06-19 16:42 UTC, AutomationD commented on charts/web/templates/deployment.yaml
> +        tags.datadoghq.com/version: {{ .Values.global.datadog.version }}
Would this break of values won't have the value? Let's say the app is deployed without monitoring.

If yes, let's add a gotmpl defaults too

2024-06-24 12:59 UTC, kobrikx commented on charts/web/values.schema.json
> +                      "type": "number"
I have just recreated schema with added parameters.

2024-06-24 13:01 UTC, kobrikx commented on charts/web/values.yaml
> +    enabled: true
Ok. But task says 
![Uploading Screenshot 2024-06-24 at 16.00.08.png…]()

2024-06-24 13:01 UTC, AutomationD commented on charts/web/values.schema.json
> +                      "type": "number"
This doesn't explain why was it integer and now number though. Pure curioucity here.

2024-06-26 09:39 UTC, kobrikx commented on charts/web/templates/deployment.yaml
> +        tags.datadoghq.com/version: {{ .Values.global.datadog.version }}
@AutomationD Could you clarify more about gotmpl and what should be done with it. 
BTW: this values should have value, cause they use global app envs that crititically needed to make deployment.
They have default settings too in the values.yaml (in web chart)

2024-06-26 10:43 UTC, AutomationD commented on charts/web/values.yaml
> +    enabled: true
FYI Screenshot is missing.

2024-06-26 10:44 UTC, DimmKirr commented on charts/web/templates/deployment.yaml
> +        tags.datadoghq.com/version: {{ .Values.global.datadog.version }}
Please see https://helm.sh/docs/chart_template_guide/functions_and_pipelines/#using-the-default-function

Let me know if you have more questions.

2024-06-26 10:55 UTC, kobrikx commented on charts/web/values.yaml
> +    enabled: true
<img width="450" alt="Screenshot 2024-06-24 at 16 00 08" src="https://github.com/hazelops/charts/assets/24703846/9b69254a-d291-4866-9c58-ba108d2656bd">

2024-06-26 10:56 UTC, kobrikx commented on charts/web/values.yaml
> +    version: "v7.54"
@AutomationD Do you mean that we need to add link to datadog explanation?

2024-06-26 10:58 UTC, kobrikx commented on charts/web/templates/deployment.yaml
> +        tags.datadoghq.com/version: {{ .Values.global.datadog.version }}
imho it's beyond the scope of this task. If we need to use gotmpl - maybe we should have started doing it earlier, and now I need time to remember and understand what needs to be done there.

2024-06-26 17:58 UTC, AutomationD commented on charts/web/values.yaml
> +    version: "v7.54"
We need to answer: where to we get the version from? How can I see what other versions are available

2024-06-26 19:01 UTC, kobrikx commented on charts/web/values.yaml
> +    version: "v7.54"
Probably this could be in help: 
https://docs.datadoghq.com/getting_started/tagging/unified_service_tagging/?tab=traces#
and this
https://docs.datadoghq.com/getting_started/tagging/unified_service_tagging/?tab=kubernetes#partial-configuration
I understand this as the Datadog (DD) version - so I check what version of Datadog agent I have and set it here.

2024-06-26 21:07 UTC, DimmKirr commented on charts/web/values.yaml
> +    version: "v7.54"
Whatever it is, please add it as a comment so next time we know where to look for a new version. 

If you have any questions please let me know.

2024-06-28 11:21 UTC, AutomationD requested changes
Please address changes I've mentioned to you in the other PR

2024-07-01 11:28 UTC, AutomationD approved these changes
Great work, thank you!

2024-09-10 09:36 UTC, merged